### ISSUE TITLE
Compile fails on USG & linux cross-compile?

### ISSUE THREAD

**Issue by MichaelAnders** [synfinatic/netflow2ng#13]
I really love this project, but I am failing to get the code compiled.

I assume that you are compiling your code directly on the USG as you did not mention any cross-compiling?

If so:
Mine does not have "go" installed. I tried it to install and it was not available. I've added these sources to sources.list (had to use the archive as wheezy is no longer maintained and I believe USG is based on wheezy?):

- deb http://archive.debian.org/debian wheezy main contrib non-free # wheezy #
- deb http://archive.debian.org wheezy main # wheezy-security #

Trying to install golang-go fails:

- sudo apt-get install golang-go
- Package golang-go is not available, but is referred to by another package.
- This may mean that the package is missing, has been obsoleted, or
- is only available from another source

So I thought I'd try to cross-compile netflow2ng for "linux mips64" on my Linux system, but that doesn't work either:
- GOOS=linux GOARCH=mips make
- ...
- # github.com/pebbe/zmq4
- ../../go/pkg/mod/github.com/pebbe/zmq4@v1.2.1/reactor.go:10:4: undefined: State

Could you shed some light on how you got yours to compile? Thx!

**Comment by synfinatic** [comment]
Basically, I don't run netflow2ng on my USG, I run it on the same box as `ntopng`.  The error you're seeing is because the Go implementation of zmq relies on the zmq C library and you need to have that available for the linux/mips64 platform: https://github.com/pebbe/zmq4/issues/157

If you really wanted to run netflow2ng on the USG (honestly it's more work than it's worth IMHO) you'd need to use a whole cross-compile toolchain.  This should give you a good idea of how to do that: https://github.com/synfinatic/udp-proxy-2020/blob/main/Dockerfile.mips64

The above does basically the same thing, but for cross-compiling libpcap instead of zmq.

**Comment by MichaelAnders** [comment]
Thanks for your reply!

I guess I misunderstood this part: "Configure your network device(s) to send NetFlow stats to netflow2ng"

So it's actually:

1. Compile netflow2g on some computer
2. Configure ntopng to collect data from netflow2ng
3. Set up the USG to send the netflow data as described e.g. [here](https://support.auvik.com/hc/en-us/articles/360025587191-How-to-configure-NetFlow-on-Ubiquiti-routers) to send the data to netflow2ng

**Comment by synfinatic** [comment]
Basically netflow2ng converts netflow packets from your USG/etc. into something that ntopng can understand.  TL;DR: [netflow2ng acts like nProbe](https://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/).  Basically:

USG ---> netflow2ng ---> ntopng

All three need to be somewhere on your network.  They could be 3 independent devices or in theory the same device.  But due to the limits of your USG, it's just easiest for most people to run ntopng and netflow2ng on the same box.

Anyways, the link you provided will work until you push a new config from the Ubiquiti controller software.  At that point all your config changes via the CLI are blown away.  To make the config changes permanent, you'll need to [edit the JSON file on the controller](https://help.ui.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration-Using-config-gateway-json).

**Comment by MichaelAnders** [comment]
Thanks a lot for the extra explanations! I saw incoming data in ntopng yesterday and will check the link you specified regarding the JSON file.
